version: '3'

services:
    role-api:
        build:
            context: ./
            dockerfile: Dockerfile
        expose:
            - 3100
        ports:
            - 3100:3001
        depends_on:
            - role-postgres
            - role-redis
            - role-minio
        links:
            - role-postgres
            - role-redis
            - role-minio
        volumes:
            - ./:/home/node/app
        command: npm run start:prod

    role-postgres:
        image: postgres:11
        restart: always

        ports:
            - 3101:5432

        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_USER}

    role-redis:
        image: 'redis:4-alpine'
        command: redis-server --requirepass ${REDIS_PASS}
        ports:
            - '3102:6379'

    role-minio:
        hostname: role-minio
        image: minio/minio:RELEASE.2021-09-18T18-09-59Z
        container_name: role-minio

        volumes:
            - './role/data/:/data'
            - './role/config:/root/.minio'

        ports:
            - 3103:9000
            - 3104:9001
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        command: server --console-address ":9001"  /data

    role-createbuckets:
        image: minio/mc
        depends_on:
            - role-minio
        entrypoint: >
            /bin/sh -c "
            sleep 10;
            /usr/bin/mc config host add data http://${MINIO_HOST}:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
            /usr/bin/mc mb data/${MINIO_BUCKET};
            /usr/bin/mc policy set public data/${MINIO_BUCKET};
            exit 0;
            "
    role-imgproxy:
        image: 'darthsim/imgproxy:latest'
        ports:
            - '3105:8080'
        depends_on:
            - role-minio
        links:
            - role-minio
        environment:
            IMGPROXY_KEY: ${IMGPROXY_KEY}
            IMGPROXY_SALT: ${IMGPROXY_SALT}
            IMGPROXY_MAX_SRC_FILE_SIZE: 10485760
